### ISSUE TITLE
Support of Elm 0.18

### ISSUE THREAD

**Issue by matrixise** [tiziano88/elm-oauth#1]

**Comment by tiziano88** [comment]
Thanks for raising this, I'm working on it, should be ready this weekend :)

**Comment by tiziano88** [comment]
This is now done, please give it a try and let me know if it works for you.

**Comment by matrixise** [comment]
thank you, I will check ;-)

**Comment by tiziano88** [comment]
Marking as closed, feel free to reopen if you encounter any issue
